# Generated by Django 3.0.7 on 2020-07-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATE', 'Investigate'), ('TRIAGE', 'Await Approval'), ('BUILD_IN_PROGRESS', 'Build in progress'), ('VALIDATE', 'Validate'), ('COMPLETE', 'Complete'), ('CLOSED', 'Closed')], default='TODO', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='upvotes',
            field=models.IntegerField(default=0, verbose_name='likes'),
        ),
    ]
