# Generated by Django 3.0.7 on 2020-07-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0003_auto_20200715_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_prefix',
            field=models.CharField(default='WINN', max_length=20),
        ),
    ]
