# Generated by Django 3.0.4 on 2020-05-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0003_auto_20200520_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('BREAK_FIX', 'Break/fix'), ('FEATURE', 'New feature'), ('OPTIMIZATION', 'Optimization')], default='BREAK_FIX', max_length=20),
        ),
    ]
