# Generated by Django 3.0.7 on 2020-07-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0004_issue_issue_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['title'], 'verbose_name': 'issue', 'verbose_name_plural': 'issues'},
        ),
        migrations.RemoveField(
            model_name='issue',
            name='tag',
        ),
        migrations.AddField(
            model_name='issue',
            name='slug',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['title'], name='itrac_issue_title_8c63b4_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['title'], name='itrac_tag_title_c88491_idx'),
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(related_name='issues', to='itrac.Tag'),
        ),
    ]
