# Generated by Django 3.0.7 on 2020-07-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0005_auto_20200717_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='issues', to='itrac.Tag'),
        ),
    ]
