# Generated by Django 3.0.7 on 2020-07-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0008_auto_20200728_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(max_length=4000),
        ),
    ]
