# Generated by Django 3.0.7 on 2020-07-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0009_auto_20200729_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
