# Generated by Django 3.0.7 on 2020-08-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0012_auto_20200818_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(default='WINN', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
