# Generated by Django 3.0.7 on 2020-08-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0013_auto_20200818_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='URL',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
