# Generated by Django 3.0.7 on 2020-08-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0014_auto_20200819_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('1', '1 - highest'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5 - lowest')], max_length=1, null=True),
        ),
    ]
