# Generated by Django 3.0.7 on 2020-08-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0015_issue_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue_prefix',
        ),
        migrations.AddField(
            model_name='issue',
            name='coded_id',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
