# Generated by Django 3.0.7 on 2020-08-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0016_auto_20200819_2334'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['coded_id'], name='itrac_issue_coded_i_2094ef_idx'),
        ),
    ]
