# Generated by Django 3.0.7 on 2020-08-21 03:28

from django.db import migrations, models
import itrac.models.project


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0017_auto_20200819_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=itrac.models.project.get_avatar_full_path),
        ),
        migrations.AddField(
            model_name='project',
            name='avatar_version',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
