# Generated by Django 3.0.7 on 2020-08-29 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0021_auto_20200821_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolution_details',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='itrac.Project'),
        ),
    ]
