# Generated by Django 3.0.7 on 2020-08-31 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0023_auto_20200830_2321'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='issuetoissuelink',
            table='itrac_issue_issue_link',
        ),
    ]
