# Generated by Django 3.0.7 on 2020-09-01 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0024_auto_20200830_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuetoissuelink',
            old_name='link_type_from',
            new_name='link_from_type',
        ),
        migrations.RenameField(
            model_name='issuetoissuelink',
            old_name='link_type_to',
            new_name='link_to_type',
        ),
    ]
