# Generated by Django 3.0.7 on 2020-09-01 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0025_auto_20200831_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuetoissuelink',
            name='link_to_type',
        ),
    ]
