# Generated by Django 3.0.7 on 2020-09-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0026_remove_issuetoissuelink_link_to_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetoissuelink',
            name='link_to_type',
            field=models.CharField(choices=[('01', 'relates to'), ('02', 'blocks'), ('03', 'is blocked by'), ('04', 'causes'), ('05', 'is caused by'), ('06', 'clones'), ('07', 'is cloned by'), ('08', 'duplicates'), ('09', 'is duplicated by')], default='01', max_length=2),
        ),
    ]
