# Generated by Django 3.1.4 on 2021-01-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0028_auto_20210111_2219'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='issueattachment',
            name='itrac_issue_descrip_1aaa27_idx',
        ),
        migrations.AddIndex(
            model_name='issueattachment',
            index=models.Index(fields=['description'], name='itrac_issue_descrip_c05756_idx'),
        ),
        migrations.AlterModelTable(
            name='issueattachment',
            table='itrac_issue_attachment',
        ),
    ]
