# Generated by Django 3.1.4 on 2021-01-16 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0030_auto_20210114_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueattachment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='itrac.issue'),
        ),
    ]
