# Generated by Django 3.1.4 on 2021-01-16 05:14

from django.db import migrations, models
import itrac.models.issue_attachment


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0031_auto_20210115_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueattachment',
            name='attachment',
            field=models.FileField(upload_to=itrac.models.issue_attachment.get_directory_path),
        ),
    ]
