# Generated by Django 3.1.4 on 2021-01-17 00:52

from django.db import migrations, models
import itrac.models.issue_attachment


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0033_auto_20210116_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueattachment',
            name='attachment',
            field=models.FileField(upload_to=itrac.models.issue_attachment.get_directory_path, validators=[itrac.models.issue_attachment.validate_file_size], verbose_name='Choose a file to upload'),
        ),
        migrations.AlterField(
            model_name='issueattachment',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
