# Generated by Django 3.1.4 on 2021-01-17 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0034_auto_20210116_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issueattachment',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'issue_attachment', 'verbose_name_plural': 'issue_attachments'},
        ),
        migrations.RemoveField(
            model_name='issue',
            name='image',
        ),
    ]
