# Generated by Django 3.1.4 on 2021-01-26 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itrac', '0035_auto_20210116_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueWatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='itrac.issue')),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'issue_watcher',
                'verbose_name_plural': 'issue_watchers',
                'db_table': 'itrac_issue_watcher',
                'ordering': ['watcher'],
            },
        ),
    ]
