# Generated by Django 3.1.4 on 2021-01-30 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itrac', '0036_issuewatcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active_ind',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='comment',
            name='active_status_cd',
            field=models.CharField(choices=[('01', 'Active'), ('02', 'Combined'), ('03', 'Historical value - combined'), ('04', 'Deleted'), ('05', 'Draft'), ('06', 'Inactive'), ('07', 'Recall'), ('08', 'Review'), ('09', 'Suspended'), ('10', 'Unknown')], default='01', max_length=2),
        ),
        migrations.AddField(
            model_name='comment',
            name='active_status_dt_tm',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='active_status_prsnl_id',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='updt_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='itrac.issue'),
        ),
        migrations.CreateModel(
            name='CommentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('updt_cnt', models.IntegerField(default=0)),
                ('updt_dt_tm', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='itrac.issue')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_hist', to='itrac.comment')),
            ],
            options={
                'verbose_name': 'comment_history',
                'verbose_name_plural': 'comment_history',
                'db_table': 'itrac_comment_hist',
                'ordering': ['-updt_dt_tm'],
            },
        ),
    ]
