# Generated by Django 3.0.7 on 2020-06-20 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDefinition',
            fields=[
                ('item_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('active_ind', models.BooleanField(default=True, verbose_name='Active')),
                ('active_status_cd', models.CharField(choices=[('01', 'Active'), ('02', 'Combined'), ('03', 'Historical value - combined'), ('04', 'Deleted'), ('05', 'Draft'), ('06', 'Inactive'), ('07', 'Recall'), ('08', 'Review'), ('09', 'Suspended'), ('10', 'Unknown')], default='01', max_length=2)),
                ('active_status_dt_tm', models.DateTimeField(blank=True, null=True)),
                ('active_status_id', models.BigIntegerField(blank=True, null=True)),
                ('approved_ind', models.BooleanField(default=False)),
                ('item_type_cd', models.CharField(choices=[('01', 'Instance'), ('02', 'Equipment Instance'), ('03', 'Equipment Master'), ('04', 'Equipment Group'), ('05', 'Manufacturer Item'), ('06', 'Item Master'), ('07', 'Vendor Item'), ('08', 'Lot Info'), ('09', 'Medication Definition'), ('10', 'Purchase Order'), ('11', 'Requisition')], default='09', max_length=2)),
                ('reusable_ind', models.BooleanField(default=False, verbose_name='Reusable')),
                ('batch_quantity', models.BigIntegerField(default=0)),
                ('chargeable_ind', models.BooleanField(default=True)),
                ('component_ind', models.BooleanField(default=True)),
                ('component_usage_ind', models.BooleanField(default=False)),
                ('create_appctx', models.BigIntegerField(default=0)),
                ('create_dt_tm', models.DateTimeField(auto_now_add=True)),
                ('create_id', models.BigIntegerField(default=0)),
                ('create_task', models.BigIntegerField(default=0)),
                ('inst_id', models.BigIntegerField(default=0)),
                ('item_level_flag', models.IntegerField(blank=True, null=True)),
                ('latex_ind', models.BooleanField(default=False)),
                ('temp_store_max', models.IntegerField(blank=True, null=True)),
                ('temp_store_min', models.IntegerField(blank=True, null=True)),
                ('temp_uom_cd', models.CharField(choices=[('C', 'degree Celsius'), ('F', 'degree Fahrenheit')], default='C', max_length=1)),
                ('shelf_life', models.IntegerField(blank=True, null=True)),
                ('shelf_life_uom_cd', models.CharField(choices=[('H', 'hours'), ('D', 'days'), ('Y', 'years')], default='H', max_length=1)),
                ('updt_cnt', models.IntegerField(default=0)),
                ('updt_dt_tm', models.DateTimeField(auto_now_add=True)),
                ('updt_id', models.BigIntegerField(default=0)),
                ('updt_task', models.BigIntegerField(default=0)),
                ('updt_appctx', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemIdentifier',
            fields=[
                ('prod_identifier_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('active_ind', models.BooleanField(default=True, verbose_name='Active')),
                ('parent_entity_id', models.IntegerField(default=0)),
                ('parent_entity_name', models.CharField(blank=True, max_length=100)),
                ('prod_identifier_type_cd', models.CharField(choices=[('01', 'Barcode'), ('02', 'Brand Name'), ('03', 'Charge Number'), ('04', 'Description'), ('05', 'Clinical Description'), ('06', 'Short Description'), ('07', 'Foreign System Item Alias'), ('08', 'Generic Name'), ('09', 'System Assigned Item Number'), ('10', 'Lot Number'), ('11', 'Manufacturer Item Number'), ('12', 'Serial Number'), ('13', 'Service Request Number'), ('14', 'Trade Name'), ('15', 'UB92 Interface Identifier'), ('16', 'Universal Product Code'), ('17', 'Universal Product Number'), ('18', 'Vendor Item Number')], max_length=2)),
                ('prod_type_flag', models.IntegerField(default=0)),
                ('primary_ind', models.BooleanField(default=False)),
                ('sequence', models.IntegerField(default=0)),
                ('updt_cnt', models.IntegerField(default=0)),
                ('updt_dt_tm', models.DateTimeField(auto_now_add=True)),
                ('updt_id', models.BigIntegerField(default=0)),
                ('updt_task', models.BigIntegerField(default=0)),
                ('updt_appctx', models.BigIntegerField(default=0)),
                ('value', models.CharField(max_length=200)),
                ('value_key', models.CharField(max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.ItemDefinition')),
            ],
        ),
        migrations.AddIndex(
            model_name='itemdefinition',
            index=models.Index(fields=['item_type_cd'], name='core_itemde_item_ty_5da7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='itemdefinition',
            index=models.Index(fields=['updt_dt_tm'], name='core_itemde_updt_dt_15edca_idx'),
        ),
        migrations.AddIndex(
            model_name='itemidentifier',
            index=models.Index(fields=['item_id'], name='core_itemid_item_id_a34980_idx'),
        ),
    ]
