# Generated by Django 3.0.4 on 2020-06-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDefinition',
            fields=[
                ('item_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('active_ind', models.BooleanField(default=True, verbose_name='Active')),
                ('active_status_cd', models.CharField(choices=[('01', 'Active'), ('02', 'Combined'), ('03', 'Historical value - combined'), ('04', 'Deleted'), ('05', 'Draft'), ('06', 'Inactive'), ('07', 'Recall'), ('08', 'Review'), ('09', 'Suspended'), ('10', 'Unknown')], default='01', max_length=2)),
                ('active_status_dt_tm', models.DateTimeField(blank=True, null=True)),
                ('active_status_id', models.BigIntegerField(blank=True, null=True)),
                ('approved_ind', models.BooleanField(default=False)),
                ('item_type_cd', models.BigIntegerField(blank=True, null=True)),
                ('reusable_ind', models.BooleanField(default=False, verbose_name='Reusable')),
                ('batch_qty', models.BigIntegerField(blank=True, null=True)),
                ('chargeable_ind', models.BooleanField(default=True)),
                ('component_ind', models.BooleanField(default=True)),
                ('component_usage_ind', models.BooleanField(default=False)),
                ('create_appctx', models.BigIntegerField(blank=True, null=True)),
                ('create_dt_tm', models.DateTimeField(auto_now_add=True)),
                ('create_id', models.BigIntegerField(blank=True, null=True)),
                ('create_task', models.BigIntegerField(blank=True, null=True)),
                ('inst_id', models.BigIntegerField(blank=True, null=True)),
                ('item_level_flag', models.IntegerField(blank=True, null=True)),
                ('latex_ind', models.BooleanField(default=False)),
                ('temp_store_max', models.IntegerField(blank=True, null=True)),
                ('temp_store_min', models.IntegerField(blank=True, null=True)),
                ('temp_uom_cd', models.CharField(choices=[('C', 'degree Celsius'), ('F', 'degree Fahrenheit')], default='C', max_length=1)),
                ('shelf_life', models.IntegerField(blank=True, null=True)),
                ('shelf_life_uom_cd', models.CharField(choices=[('H', 'hours'), ('D', 'days'), ('Y', 'years')], default='H', max_length=1)),
                ('updt_cnt', models.IntegerField(blank=True, null=True)),
                ('updt_dt_tm', models.DateTimeField(blank=True, null=True)),
                ('updt_id', models.BigIntegerField(blank=True, null=True)),
                ('updt_task', models.BigIntegerField(blank=True, null=True)),
                ('updt_appctx', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='itemdefinition',
            index=models.Index(fields=['item_type_cd'], name='core_itemde_item_ty_5da7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='itemdefinition',
            index=models.Index(fields=['updt_dt_tm'], name='core_itemde_updt_dt_15edca_idx'),
        ),
    ]
