# Generated by Django 3.0.7 on 2020-06-20 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdefinition',
            old_name='active_status_id',
            new_name='active_status_prsnl_id',
        ),
        migrations.RenameField(
            model_name='itemidentifier',
            old_name='prod_identifier_id',
            new_name='item_identifier_id',
        ),
        migrations.RenameField(
            model_name='itemidentifier',
            old_name='prod_identifier_type_cd',
            new_name='item_identifier_type_cd',
        ),
        migrations.RenameField(
            model_name='itemidentifier',
            old_name='prod_type_flag',
            new_name='item_type_flag',
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('item_price_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('active_ind', models.BooleanField(default=True, verbose_name='Active')),
                ('active_status_cd', models.CharField(choices=[('01', 'Active'), ('02', 'Combined'), ('03', 'Historical value - combined'), ('04', 'Deleted'), ('05', 'Draft'), ('06', 'Inactive'), ('07', 'Recall'), ('08', 'Review'), ('09', 'Suspended'), ('10', 'Unknown')], default='01', max_length=2)),
                ('active_status_dt_tm', models.DateTimeField(blank=True, null=True)),
                ('active_status_prsnl_id', models.BigIntegerField(blank=True, null=True)),
                ('contract_description', models.CharField(max_length=100)),
                ('contract_id', models.BigIntegerField(default=0)),
                ('contract_line_id', models.BigIntegerField(default=0)),
                ('contract_nbr', models.CharField(blank=True, max_length=40)),
                ('contract_type', models.CharField(blank=True, max_length=100)),
                ('contributor_system_cd', models.BigIntegerField(default=0)),
                ('create_appctx', models.BigIntegerField(default=0)),
                ('create_dt_tm', models.DateTimeField(auto_now_add=True)),
                ('create_id', models.BigIntegerField(default=0)),
                ('create_task', models.BigIntegerField(default=0)),
                ('effective_dt_tm', models.DateTimeField(auto_now_add=True)),
                ('expiration_dt_tm', models.DateTimeField(blank=True, null=True)),
                ('fixed_price_ind', models.BooleanField(default=True, verbose_name='Price Fixed')),
                ('min_order_quantity', models.BigIntegerField(default=0)),
                ('order_qty_multiple', models.IntegerField(default=0)),
                ('organization_id', models.BigIntegerField(default=0)),
                ('package_type_id', models.BigIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_quote_source', models.CharField(blank=True, max_length=100)),
                ('price_type_cd', models.CharField(choices=[('01', 'Contract'), ('02', 'List'), ('03', 'Quote')], default='03', max_length=2)),
                ('updt_cnt', models.IntegerField(default=0)),
                ('updt_dt_tm', models.DateTimeField(auto_now_add=True)),
                ('updt_id', models.BigIntegerField(default=0)),
                ('updt_task', models.BigIntegerField(default=0)),
                ('updt_appctx', models.BigIntegerField(default=0)),
                ('vendor_price_schedule_id', models.BigIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.ItemDefinition')),
            ],
        ),
        migrations.AddIndex(
            model_name='itemprice',
            index=models.Index(fields=['item'], name='core_itempr_item_id_091a37_idx'),
        ),
        migrations.AddIndex(
            model_name='itemprice',
            index=models.Index(fields=['contract_line_id'], name='core_itempr_contrac_11f5b0_idx'),
        ),
    ]
