# Generated by Django 3.0.4 on 2020-06-19 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdefinition',
            name='create_appctx',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemdefinition',
            name='create_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemdefinition',
            name='create_task',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemdefinition',
            name='item_type_cd',
            field=models.CharField(choices=[('01', 'Instance'), ('02', 'Equipment Instance'), ('03', 'Equipment Master'), ('04', 'Equipment Group'), ('05', 'Manufacturer Item'), ('06', 'Item Master'), ('07', 'Vendor Item'), ('08', 'Lot Info'), ('09', 'Medication Definition'), ('10', 'Purchase Order'), ('11', 'Requisition')], default='09', max_length=2),
        ),
        migrations.AlterField(
            model_name='itemdefinition',
            name='updt_dt_tm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
