# Generated by Django 3.0.7 on 2020-06-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200619_2228'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='itemidentifier',
            name='core_itemid_item_id_a34980_idx',
        ),
        migrations.AlterField(
            model_name='itemidentifier',
            name='item_type_flag',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddIndex(
            model_name='itemidentifier',
            index=models.Index(fields=['item'], name='core_itemid_item_id_a34980_idx'),
        ),
    ]
