# Generated by Django 3.0.7 on 2020-07-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200701_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprice',
            name='create_dt_tm',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
