# Generated by Django 3.0.4 on 2020-06-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200619_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdefinition',
            name='batch_qty',
        ),
        migrations.AddField(
            model_name='itemdefinition',
            name='batch_quantity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemdefinition',
            name='inst_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
