# Generated by Django 3.0.8 on 2020-10-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200702_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeValue',
            fields=[
                ('code_value', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('definition', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('display', models.CharField(max_length=100)),
                ('code_set', models.IntegerField(default=0)),
                ('active_ind', models.BooleanField(default=True, verbose_name='Active')),
                ('active_dt_tm', models.DateTimeField(blank=True, null=True)),
                ('begin_effective_dt_tm', models.DateTimeField(blank=True)),
                ('end_effevtive_dt_tm', models.DateTimeField(blank=True)),
                ('inactivate_dt_tm', models.DateTimeField(blank=True)),
                ('display_sequence', models.IntegerField(default=0)),
                ('wki', models.CharField(blank=True, max_length=255, null=True, verbose_name='Winn Knowledge Index')),
                ('concept_wki', models.CharField(blank=True, max_length=255, null=True, verbose_name='Concept WKI')),
                ('create_dt_tm', models.DateTimeField(auto_now_add=True)),
                ('create_id', models.BigIntegerField(default=0)),
                ('updt_cnt', models.IntegerField(default=0)),
                ('updt_dt_tm', models.DateTimeField(auto_now=True)),
                ('updt_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'core_code_value',
            },
        ),
        migrations.CreateModel(
            name='CodeValueSet',
            fields=[
                ('code_set', models.IntegerField(primary_key=True, serialize=False)),
                ('display', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('definition', models.CharField(max_length=100)),
                ('active_ind', models.BooleanField(default=True, verbose_name='Active')),
                ('cache_ind', models.BooleanField(default=False, verbose_name='Cached')),
                ('change_access_ind', models.BooleanField(default=True, verbose_name='Change Allowed ')),
                ('create_dt_tm', models.DateTimeField(auto_now_add=True)),
                ('create_id', models.BigIntegerField(default=0)),
                ('updt_cnt', models.IntegerField(default=0)),
                ('updt_dt_tm', models.DateTimeField(auto_now=True)),
                ('updt_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'core_code_value_set',
            },
        ),
        migrations.AddIndex(
            model_name='codevalueset',
            index=models.Index(fields=['code_set'], name='cvs_code_set_idx'),
        ),
        migrations.AddIndex(
            model_name='codevalueset',
            index=models.Index(fields=['display'], name='cvs_display_idx'),
        ),
        migrations.AddIndex(
            model_name='codevalue',
            index=models.Index(fields=['code_set'], name='cv_code_set_idx'),
        ),
        migrations.AddIndex(
            model_name='codevalue',
            index=models.Index(fields=['display'], name='cv_display_idx'),
        ),
    ]
