# Generated by Django 3.0.7 on 2020-06-20 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200620_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdefinition',
            name='create_dt_tm',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='create_dt_tm',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itempricehist',
            name='create_dt_tm',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
