# Generated by Django 3.0.8 on 2020-10-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201018_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codevalueset',
            name='code_set',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
