# Generated by Django 3.0.8 on 2020-10-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201018_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codevalue',
            old_name='end_effevtive_dt_tm',
            new_name='end_effective_dt_tm',
        ),
        migrations.AlterField(
            model_name='codevalueset',
            name='code_set',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
