# Generated by Django 3.0.7 on 2020-06-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200620_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdefinition',
            name='active_status_prsnl_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemdefinition',
            name='create_applabel',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemdefinition',
            name='item_type_cd',
            field=models.CharField(choices=[('01', 'Instance'), ('02', 'Equipment Instance'), ('03', 'Equipment Master'), ('04', 'Equipment Group'), ('05', 'Manufacturer Item'), ('06', 'Item Master'), ('07', 'Vendor Item'), ('08', 'Lot Info'), ('09', 'Medication Definition'), ('10', 'Purchase Order'), ('11', 'Requisition'), ('12', 'General'), ('13', 'Produce')], default='12', max_length=2, verbose_name='Item Type'),
        ),
        migrations.AlterField(
            model_name='itemdefinition',
            name='shelf_life_uom_cd',
            field=models.CharField(choices=[('H', 'hours'), ('D', 'days'), ('Y', 'years')], default='H', max_length=1, verbose_name='Shelf Life UOM'),
        ),
        migrations.AlterField(
            model_name='itemdefinition',
            name='updt_applabel',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemidentifier',
            name='item_identifier_type_cd',
            field=models.CharField(choices=[('01', 'Barcode'), ('02', 'Brand Name'), ('03', 'Charge Number'), ('04', 'Description'), ('05', 'Clinical Description'), ('06', 'Short Description'), ('07', 'Foreign System Item Alias'), ('08', 'Generic Name'), ('09', 'System Assigned Item Number'), ('10', 'Lot Number'), ('11', 'Manufacturer Item Number'), ('12', 'Serial Number'), ('13', 'Service Request Number'), ('14', 'Trade Name'), ('15', 'UB92 Interface Identifier'), ('16', 'Universal Product Code'), ('17', 'Universal Product Number'), ('18', 'Vendor Item Number')], max_length=2, verbose_name='Item Identifier Type'),
        ),
        migrations.AlterField(
            model_name='itemidentifier',
            name='updt_applabel',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='active_status_prsnl_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='contract_description',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='contract_nbr',
            field=models.CharField(default='none', max_length=40),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='contract_type',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='create_applabel',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='price_quote_source',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='updt_applabel',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
