# Generated by Django 3.0.7 on 2020-06-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200620_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdefinition',
            name='description',
            field=models.CharField(default='test', max_length=40),
            preserve_default=False,
        ),
    ]
