# Generated by Django 3.0.8 on 2020-10-18 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201018_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codevalue',
            name='begin_effective_dt_tm',
            field=models.DateTimeField(blank=True, verbose_name='Begin Effective Date/Time'),
        ),
        migrations.AlterField(
            model_name='codevalue',
            name='code_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_code_values', to='core.CodeValueSet'),
        ),
        migrations.AlterField(
            model_name='codevalue',
            name='end_effective_dt_tm',
            field=models.DateTimeField(blank=True, verbose_name='End Effective Date/Time'),
        ),
        migrations.AlterField(
            model_name='codevalue',
            name='wki',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Winn Knowledge Index(WKI)'),
        ),
    ]
