# Generated by Django 3.0.8 on 2020-10-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201018_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codevalue',
            name='begin_effective_dt_tm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Begin Effective Date/Time'),
        ),
        migrations.AlterField(
            model_name='codevalue',
            name='end_effective_dt_tm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Effective Date/Time'),
        ),
    ]
