# Generated by Django 3.0.7 on 2020-06-20 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200620_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBarcode',
            fields=[
                ('item_barcode_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('active_ind', models.BooleanField(default=True, verbose_name='Active')),
                ('parent_entity_id', models.IntegerField(default=0)),
                ('parent_entity_name', models.CharField(blank=True, max_length=100)),
                ('item_barcode_type_cd', models.CharField(choices=[('20', 'Barcode'), ('21', 'Charge Number'), ('22', 'System Assigned Item Number'), ('23', 'Lot Number'), ('24', 'Manufacturer Item Number'), ('25', 'Serial Number'), ('26', 'Service Request Number'), ('27', 'UB92 Interface Identifier'), ('28', 'Universal Product Code'), ('29', 'Universal Product Number'), ('30', 'Vendor Item Number')], default='20', max_length=2, verbose_name='Item Barcode Type')),
                ('item_type_flag', models.IntegerField(default=0)),
                ('primary_ind', models.BooleanField(default=False)),
                ('sequence', models.IntegerField(default=0)),
                ('updt_cnt', models.IntegerField(default=0)),
                ('updt_dt_tm', models.DateTimeField(auto_now=True)),
                ('updt_id', models.BigIntegerField(default=0)),
                ('updt_task', models.BigIntegerField(default=0)),
                ('updt_applabel', models.CharField(default='0', max_length=20)),
                ('value', models.CharField(max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.ItemDefinition')),
            ],
        ),
        migrations.AddIndex(
            model_name='itembarcode',
            index=models.Index(fields=['item'], name='core_itemba_item_id_5211a8_idx'),
        ),
        migrations.AddIndex(
            model_name='itembarcode',
            index=models.Index(fields=['value'], name='core_itemba_value_655a10_idx'),
        ),
    ]
