# Generated by Django 3.0.8 on 2020-10-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201018_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codevalue',
            name='wki',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='WKI'),
        ),
        migrations.AlterField(
            model_name='item',
            name='active_status_cd',
            field=models.CharField(choices=[('01', 'Active'), ('02', 'Combined'), ('03', 'Historical value - combined'), ('04', 'Deleted'), ('05', 'Draft'), ('06', 'Inactive'), ('07', 'Recall'), ('08', 'Review'), ('09', 'Suspended'), ('10', 'Unknown')], default='01', max_length=2, verbose_name='Active Status'),
        ),
    ]
