# Generated by Django 3.0.7 on 2020-06-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200620_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembarcode',
            name='primary_ind',
            field=models.BooleanField(default=True, verbose_name='Primary Code'),
        ),
    ]
