# Generated by Django 3.0.8 on 2020-10-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201018_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='codevalue',
            name='wdf_meaning',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Meaning'),
        ),
    ]
