# Generated by Django 3.0.8 on 2020-11-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_codevalue_wdf_meaning'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='codevalue',
            name='cv_code_set_idx',
        ),
        migrations.AddIndex(
            model_name='codevalue',
            index=models.Index(fields=['code_set', 'definition'], name='cv_code_set_idx'),
        ),
    ]
