# Generated by Django 3.0.7 on 2020-06-20 23:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200620_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdefinition',
            name='active_status_dt_tm',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itemidentifier',
            name='item_identifier_type_cd',
            field=models.CharField(choices=[('01', 'Brand Name'), ('02', 'Description'), ('03', 'Clinical Description'), ('04', 'Short Description'), ('05', 'Foreign System Item Alias'), ('06', 'Generic Name'), ('07', 'Trade Name')], default='01', max_length=2, verbose_name='Item Identifier Type'),
        ),
    ]
