# Generated by Django 3.0.7 on 2020-06-21 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200620_1645'),
    ]

    operations = [
        migrations.RunSQL('ALTER SEQUENCE CORE_ITEMDEFINITION_item_id_seq RESTART WITH 10000;')
    ]
