# Generated by Django 3.0.7 on 2020-06-21 00:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200620_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('active_ind', models.BooleanField(default=True, verbose_name='Active')),
                ('active_status_cd', models.CharField(choices=[('01', 'Active'), ('02', 'Combined'), ('03', 'Historical value - combined'), ('04', 'Deleted'), ('05', 'Draft'), ('06', 'Inactive'), ('07', 'Recall'), ('08', 'Review'), ('09', 'Suspended'), ('10', 'Unknown')], default='01', max_length=2)),
                ('active_status_dt_tm', models.DateTimeField(default=django.utils.timezone.now)),
                ('active_status_prsnl_id', models.BigIntegerField(default=0)),
                ('approved_ind', models.BooleanField(default=False)),
                ('item_type_cd', models.CharField(choices=[('12', 'General'), ('13', 'Produce'), ('14', 'Dairy'), ('03', 'Equipment Master'), ('04', 'Equipment Group'), ('05', 'Manufacturer Item'), ('06', 'Item Master'), ('07', 'Vendor Item'), ('08', 'Lot Info'), ('09', 'Medication'), ('10', 'Purchase Order'), ('11', 'Requisition'), ('01', 'Instance'), ('02', 'Equipment Instance')], default='12', max_length=2, verbose_name='Item Type')),
                ('reusable_ind', models.BooleanField(default=False, verbose_name='Reusable')),
                ('batch_quantity', models.BigIntegerField(default=0)),
                ('chargeable_ind', models.BooleanField(default=True)),
                ('component_ind', models.BooleanField(default=True)),
                ('component_usage_ind', models.BooleanField(default=False)),
                ('create_applabel', models.CharField(default='0', max_length=20)),
                ('create_dt_tm', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_id', models.BigIntegerField(default=0)),
                ('create_task', models.BigIntegerField(default=0)),
                ('description', models.CharField(max_length=40)),
                ('inst_id', models.BigIntegerField(default=0)),
                ('item_level_flag', models.IntegerField(blank=True, null=True)),
                ('latex_ind', models.BooleanField(default=False)),
                ('temp_store_max', models.IntegerField(blank=True, null=True)),
                ('temp_store_min', models.IntegerField(blank=True, null=True)),
                ('temp_uom_cd', models.CharField(choices=[('C', 'degree Celsius'), ('F', 'degree Fahrenheit')], default='C', max_length=1)),
                ('shelf_life', models.IntegerField(blank=True, null=True)),
                ('shelf_life_uom_cd', models.CharField(choices=[('H', 'hours'), ('D', 'days'), ('Y', 'years')], default='H', max_length=1, verbose_name='Shelf Life UOM')),
                ('updt_cnt', models.IntegerField(default=0)),
                ('updt_dt_tm', models.DateTimeField(auto_now=True)),
                ('updt_id', models.BigIntegerField(default=0)),
                ('updt_task', models.BigIntegerField(default=0)),
                ('updt_applabel', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_type_cd'], name='core_item_item_ty_dcfb86_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['updt_dt_tm'], name='core_item_updt_dt_396218_idx'),
        ),
        migrations.AlterField(
            model_name='itembarcode',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Item'),
        ),
        migrations.AlterField(
            model_name='itemidentifier',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.Item'),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Item'),
        ),
        migrations.AlterField(
            model_name='itempricehist',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Item'),
        ),
        migrations.DeleteModel(
            name='ItemDefinition',
        ),
    ]
