# Generated by Django 3.0.7 on 2020-06-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200620_1759'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='itemprice',
            name='item_price_item_id_4d4cb0_idx',
        ),
        migrations.RemoveIndex(
            model_name='itemprice',
            name='item_price_contrac_17515c_idx',
        ),
        migrations.AddIndex(
            model_name='itemprice',
            index=models.Index(fields=['item'], name='core_item_p_item_id_8f2dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='itemprice',
            index=models.Index(fields=['contract_line_id'], name='core_item_p_contrac_d1f638_idx'),
        ),
        migrations.AlterModelTable(
            name='itemprice',
            table='core_item_price',
        ),
    ]
