# Generated by Django 3.0.7 on 2020-06-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200620_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemidentifier',
            name='item_identifier_type_cd',
            field=models.CharField(choices=[('01', 'Brand Name'), ('02', 'Description'), ('03', 'Clinical Description'), ('04', 'Short Description'), ('05', 'Foreign System Item Alias'), ('06', 'Generic Name'), ('07', 'Trade Name')], default='02', max_length=2, verbose_name='Item Identifier Type'),
        ),
    ]
