# Generated by Django 3.0.7 on 2020-06-28 06:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200621_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='itembarcode',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Barcodes', to='core.Item'),
        ),
        migrations.AlterField(
            model_name='itemidentifier',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Identifiers', to='core.Item'),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prices', to='core.Item'),
        ),
    ]
