# Generated by Django 3.0.7 on 2020-06-28 06:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200627_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('client_id', models.BigIntegerField(default=0)),
                ('coupon_used_ind', models.BooleanField(default=False, verbose_name='Coupon Used')),
                ('coupon_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_mode_cd', models.CharField(choices=[('01', 'Scan-N-Pay'), ('02', 'ESI'), ('03', 'Direct Entry'), ('04', 'Cashier')], default='01', max_length=2, verbose_name='Entry Mode')),
                ('parent_entity_id', models.IntegerField(default=0)),
                ('parent_entity_name', models.CharField(blank=True, max_length=100)),
                ('performed_dt_tm', models.DateTimeField(blank=True)),
                ('performed_prsnl_id', models.BigIntegerField(default=0)),
                ('person_id', models.BigIntegerField(default=0)),
                ('sequence', models.IntegerField(default=0)),
                ('trans_comment_ind', models.BooleanField(default=False, verbose_name='Active')),
                ('trans_dt_tm', models.DateTimeField(auto_now=True)),
                ('trans_event_tag', models.DateTimeField(auto_now=True)),
                ('trans_event_title', models.DateTimeField(auto_now=True)),
                ('trans_type', models.CharField(choices=[('01', 'Purchase'), ('02', 'Refund'), ('03', 'Exchange')], default='01', max_length=2, verbose_name='Transaction Type')),
                ('trans_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_quantity', models.IntegerField(default=0)),
                ('total_orig_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updt_cnt', models.IntegerField(default=0)),
                ('updt_dt_tm', models.DateTimeField(auto_now=True)),
                ('updt_id', models.BigIntegerField(default=0)),
                ('updt_task', models.BigIntegerField(default=0)),
                ('updt_applabel', models.CharField(default='0', max_length=20)),
                ('workstation_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'core_transaction',
            },
        ),
        migrations.CreateModel(
            name='TransComment',
            fields=[
                ('trans_comment_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('action_sequence', models.IntegerField(default=0)),
                ('comment_dt_tm', models.DateTimeField(auto_now=True)),
                ('comment_prsnl_id', models.BigIntegerField(default=0)),
                ('comment_type_cd', models.CharField(choices=[('01', 'Staff Comment'), ('02', 'Client Comment'), ('03', 'Audit Comment'), ('04', 'System Comment'), ('05', 'Void Reason')], max_length=2, verbose_name='Comment Type')),
                ('comment', models.TextField(blank=True, null=True)),
                ('display_mask', models.IntegerField(default=0)),
                ('updt_cnt', models.IntegerField(default=0)),
                ('updt_dt_tm', models.DateTimeField(auto_now=True)),
                ('updt_id', models.BigIntegerField(default=0)),
                ('updt_task', models.BigIntegerField(default=0)),
                ('updt_applabel', models.CharField(default='0', max_length=20)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='core.Transaction')),
            ],
            options={
                'db_table': 'core_trans_comment',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['performed_dt_tm'], name='core_transa_perform_6c141b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['person_id'], name='core_transa_person__b4b1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['performed_prsnl_id'], name='core_transa_perform_76ea82_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['trans_dt_tm'], name='core_transa_trans_d_4a6b14_idx'),
        ),
        migrations.AddIndex(
            model_name='transcomment',
            index=models.Index(fields=['transaction_id'], name='core_trans__transac_f26553_idx'),
        ),
    ]
