# Generated by Django 3.0.7 on 2020-06-29 02:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200628_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='valid_until_dt_tm',
            field=models.DateTimeField(default=datetime.datetime(2150, 12, 31, 0, 0, tzinfo=utc)),
        ),
    ]
