# Generated by Django 3.0.7 on 2020-06-29 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200628_1902'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_trans_d_4a6b14_idx',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='trans_dt_tm',
            new_name='trans_end_dt_tm',
        ),
        migrations.AddField(
            model_name='transaction',
            name='authentic_flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trans_event_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trans_start_dt_tm',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='parent_entity_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['trans_end_dt_tm'], name='core_transa_trans_e_c4a25d_idx'),
        ),
    ]
