# Generated by Django 3.0.7 on 2020-06-20 03:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name_first', models.CharField(default='John', max_length=128, verbose_name='Fist Name')),
                ('name_middle', models.CharField(blank=True, max_length=128, null=True, verbose_name='Middle Name')),
                ('name_last', models.CharField(default='Doe', max_length=128, verbose_name='Last Name')),
                ('name_full_formatted', models.CharField(default='John Doe, MD', max_length=128, verbose_name='Full Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('active_status_cd', models.IntegerField(default=1, verbose_name='Active Status')),
                ('active_status_dt_tm', models.DateTimeField(auto_now_add=True, verbose_name='Active Status Date')),
                ('person_type_cd', models.IntegerField(default=1, verbose_name='User Type')),
                ('created_dt_tm', models.DateTimeField(blank=True, null=True, verbose_name='Date Created')),
                ('create_id', models.BigIntegerField(blank=True, null=True, verbose_name='Created by')),
                ('updated_dt_tm', models.DateTimeField(blank=True, null=True, verbose_name='Date Updated')),
                ('update_id', models.BigIntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('user', models.OneToOneField(help_text='Each person must have a username which is used to login to the system', limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
            options={
                'verbose_name': 'Person',
                'ordering': ['name_last'],
            },
        ),
        migrations.CreateModel(
            name='Prsnl',
            fields=[
                ('prsnl_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('active_status_cd', models.IntegerField(default=1, verbose_name='Ative Status')),
                ('name_first', models.CharField(blank=True, max_length=128, verbose_name='Fist Name')),
                ('name_middle', models.CharField(blank=True, max_length=128, verbose_name='Middle Name')),
                ('name_last', models.CharField(blank=True, max_length=128, verbose_name='Last Name')),
                ('name_full_formatted', models.CharField(blank=True, max_length=128, verbose_name='Full Name')),
                ('colour_code', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('orange', 'Orange'), ('green', 'Green')], default='green', help_text='The colour of their care team(not their skin colour)', max_length=6)),
                ('position', models.CharField(choices=[('P01', 'Physician - General Medicine'), ('P02', 'Physician - Critical Care'), ('P03', 'Physician - Emergency'), ('N01', 'Nurse'), ('N02', 'Nurse - ICU'), ('N03', 'Nurse - Emergency'), ('N04', 'Nurse - Ambulatory'), ('CEO', 'Chief Executive Officer'), ('CFO', 'Chief Financial Officer'), ('COO', 'Chief Operating Officer'), ('M01', 'General Manager')], default='N01', max_length=3)),
                ('user', models.OneToOneField(help_text='Each staff member must have a username which is used to login to the Winter Winn system', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
            },
        ),
        migrations.CreateModel(
            name='Prsnl_Alias',
            fields=[
                ('prsnl_alias_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=1, verbose_name='Active')),
                ('active_status_cd', models.IntegerField(default=1, verbose_name='Ative Status')),
                ('alias', models.CharField(default='abc', max_length=200, verbose_name='Alias')),
                ('alias_expiry_dt_tm', models.DateTimeField(blank=True, null=True, verbose_name='Alias Expiry Date')),
                ('alias_pool_cd', models.IntegerField(default=1, verbose_name='Alias Type')),
                ('prsnl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Prsnl')),
            ],
        ),
        migrations.CreateModel(
            name='Person_Alias',
            fields=[
                ('person_alias_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('active_status_cd', models.IntegerField(default=1, verbose_name='Ative Status')),
                ('alias', models.CharField(default='abc', max_length=200, verbose_name='Alias')),
                ('alias_expiry_dt_tm', models.DateTimeField(blank=True, null=True, verbose_name='Alias Expiry Date')),
                ('alias_pool_cd', models.IntegerField(default=1, verbose_name='Alias Type')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Person')),
            ],
        ),
    ]
