# Generated by Django 3.0.2 on 2020-02-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(max_length=128)),
                ('name_middle', models.CharField(max_length=128)),
                ('name_last', models.CharField(max_length=128)),
                ('name_full_fromatted', models.CharField(max_length=128)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
