# Generated by Django 3.0.2 on 2020-02-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name_middle',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
