# Generated by Django 3.0.2 on 2020-02-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200223_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name_middle',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
