# Generated by Django 3.0.2 on 2020-02-23 11:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200223_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AddField(
            model_name='person',
            name='person_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_first',
            field=models.CharField(max_length=128, verbose_name='Fist Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_full_formatted',
            field=models.CharField(max_length=128, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_last',
            field=models.CharField(max_length=128, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_middle',
            field=models.CharField(blank=True, max_length=128, verbose_name='Middle Name'),
        ),
    ]
