# Generated by Django 3.0.3 on 2020-02-23 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200223_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='active_status_cd',
            field=models.IntegerField(default=1, verbose_name='Active Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='active_status_dttm',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Active Status Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='created_dttm',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='person_type_cd',
            field=models.IntegerField(default=1, verbose_name='User Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='update_dttm',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Updated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='update_id',
            field=models.IntegerField(default=1, verbose_name='Updated by'),
            preserve_default=False,
        ),
    ]
