# Generated by Django 3.0.8 on 2020-10-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='p_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['display'], name='p_display_idx'),
        ),
    ]
