# Generated by Django 3.0.8 on 2020-10-20 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_codevalue_wdf_meaning'),
        ('shop', '0002_auto_20201018_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_cd',
            field=models.ForeignKey(limit_choices_to={'active_ind': 1, 'code_set': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.CodeValue', verbose_name='Category'),
        ),
    ]
