# Generated by Django 3.0.8 on 2020-10-22 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201019_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': (('can_load_shop_data', 'can_delete_shop_data'),)},
        ),
    ]
