# Generated by Django 3.0.8 on 2020-11-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
