# Generated by Django 3.0.8 on 2020-11-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201107_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('create_dt_tm', models.DateTimeField(auto_now_add=True)),
                ('create_id', models.BigIntegerField(default=0)),
                ('updt_cnt', models.IntegerField(default=0)),
                ('updt_dt_tm', models.DateTimeField(auto_now=True)),
                ('updt_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'shop_payment',
                'ordering': ('-create_dt_tm',),
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['description'], name='shop_paymen_descrip_e4adf0_idx'),
        ),
    ]
