# Generated by Django 3.0.8 on 2020-11-14 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20201108_2339'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='shop_order_payment_49f7f9_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shop.Order'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['description'], name='shop_order_descrip_52e4d2_idx'),
        ),
    ]
