# Generated by Django 3.0.8 on 2020-11-14 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_codevalue_wdf_meaning'),
        ('shop', '0017_auto_20201113_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active_ind',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='order',
            name='ordert_status',
            field=models.ForeignKey(default=7, limit_choices_to={'active_ind': 1, 'code_set': 4}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.CodeValue', verbose_name='Order Status'),
            preserve_default=False,
        ),
    ]
