# Generated by Django 3.0.8 on 2020-11-15 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20201113_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordert_status',
            new_name='order_status',
        ),
    ]
