# Generated by Django 3.1.4 on 2021-01-05 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201114_1814'),
        ('shop', '0019_auto_20201114_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_cd',
            field=models.ForeignKey(limit_choices_to={'active_ind': 1, 'code_set': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.codevalue', verbose_name='category'),
        ),
    ]
