# Generated by Django 3.0.4 on 2020-05-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['name']},
        ),
    ]
