# Generated by Django 3.0.4 on 2020-03-21 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated1_by',
            new_name='updated_by',
        ),
    ]
